export const LANGUAGE_OPTIONS = [
  { code: "auto", label: "自动检测" },
  { code: "zh-CN", label: "简体中文" },
  { code: "zh-TW", label: "繁體中文" },
  { code: "en", label: "English 英语" },
  { code: "ja", label: "日本語" },
  { code: "ko", label: "한국어 韩语" },
  { code: "de", label: "Deutsch 德语" },
  { code: "fr", label: "Français 法语" },
  { code: "es", label: "Español 西班牙语" },
  { code: "pt", label: "Português 葡萄牙语" },
  { code: "ru", label: "Русский 俄语" },
  { code: "it", label: "Italiano 意大利语" },
  { code: "vi", label: "Tiếng Việt 越南语" },
  { code: "th", label: "ไทย 泰语" },
  { code: "id", label: "Bahasa Indonesia 印尼语" },
  { code: "ms", label: "Bahasa Melayu 马来语" },
  { code: "tr", label: "Türkçe 土耳其语" },
  { code: "ar", label: "العربية 阿拉伯语" },
  { code: "hi", label: "हिन्दी 印地语" },
  { code: "nl", label: "Nederlands 荷兰语" },
  { code: "pl", label: "Polski 波兰语" },
  { code: "uk", label: "Українська 乌克兰语" },
  { code: "sv", label: "Svenska 瑞典语" },
  { code: "da", label: "Dansk 丹麦语" },
  { code: "fi", label: "Suomi 芬兰语" },
  { code: "no", label: "Norsk 挪威语" },
  { code: "cs", label: "Čeština 捷克语" },
  { code: "ro", label: "Română 罗马尼亚语" },
  { code: "hu", label: "Magyar 匈牙利语" },
  { code: "el", label: "Ελληνικά 希腊语" },
  { code: "he", label: "עברית 希伯来语" },
  { code: "fa", label: "فارسی 波斯语" },
  { code: "bn", label: "বাংলা 孟加拉语" },
  { code: "fil", label: "Filipino 菲律宾语" }
];

export function languageLabel(code) {
  return LANGUAGE_OPTIONS.find((item) => item.code === code)?.label || code || "";
}
